"""add_calendar_event_id_to_appointments

Revision ID: 4803e951ab6d
Revises: 0a6da71a9b82
Create Date: 2026-01-17 11:16:51.491064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4803e951ab6d'
down_revision = '0a6da71a9b82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('calendar_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'calendar_event_id')
    # ### end Alembic commands ###
